variable "display_name" {
  description = "Display name of the entitlement management catalog."
  type        = string

  validation {
    condition     = length(var.display_name) > 0 && length(var.display_name) <= 90
    error_message = "display_name must be between 1 and 90 characters."
  }
}

variable "description" {
  description = "Description of the entitlement management catalog."
  type        = string
  default     = null
}

variable "state" {
  description = "Whether the catalog is published and available for management. One of \"unpublished\" or \"published\"."
  type        = string
  default     = "unpublished"

  validation {
    condition     = contains(["unpublished", "published"], var.state)
    error_message = "state must be one of \"unpublished\" or \"published\"."
  }
}

variable "catalog_type" {
  description = "Whether the catalog is created by a user or generated by default for a service. One of \"userManaged\" or \"serviceDefault\"."
  type        = string
  default     = "userManaged"

  validation {
    condition     = contains(["userManaged", "serviceDefault"], var.catalog_type)
    error_message = "catalog_type must be one of \"userManaged\" or \"serviceDefault\"."
  }
}

variable "api_version" {
  description = "Microsoft Graph API version to target for the catalogs endpoint. One of \"v1.0\" or \"beta\"."
  type        = string
  default     = "v1.0"

  validation {
    condition     = contains(["v1.0", "beta"], var.api_version)
    error_message = "api_version must be one of \"v1.0\" or \"beta\"."
  }
}
